### ISSUE TITLE
Level parameter does not seem to work

### ISSUE THREAD

**Issue by ghost** [BradCrumb/atom-linter-phpstan#1]
The level parameter does not seem to be passed to PHPStan.

I think this is due to the value being saved and returned as string, whilst the `levels` array contains integers, due to which the `indexOf` seems to always return false.

Thanks!

**Comment by BradCrumb** [comment]
Hi @tominventisbe,

Thanks for using my linter.

I just fixed the level parameter and released 1.0.1.
