### ISSUE TITLE
PHPStan does not work with UNC paths on Windows

### ISSUE THREAD

**Issue by jt-github** [BradCrumb/atom-linter-phpstan#15]
If this is a true PHPStan issue and not an atom-linter-phpstan issue, please let me know and I'll move it to PHPStan's bug list.

I am running a CentOS 7 instance using Windows Subsystem for Linux (WSL) on my Windows 10 PC.  Atom is running in Windows and accesses the CentOS 7 files using a UNC: \\wsl$\CentOS7\my\files\here (which provides access to /my/files/here in the Linux file system)

It seems that UNC paths are unsupported.

The following error appears in the Atom (Chrome) dev tools console:
```
[Linter] Error running PHPStan Error: '\\wsl$\CentOS7\my\files\here'
CMD.EXE was started with the above path as the current directory.
UNC paths are not supported.  Defaulting to Windows directory.
Path C:\Windows\wsl$\CentOS7\my\files\here\somefile.php does not exist
    at ChildProcess.<anonymous> (C:\Users\me\.atom\packages\atom-linter-phpstan\node_modules\sb-exec\lib\index.js:56:20)
    at ChildProcess.emit (events.js:194:13)
    at maybeClose (internal/child_process.js:998:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:265:5)
```

**Comment by mallardduck** [comment]
Based on what I'm seeing with some quick research this is Windows reporting the error, it bubbles up through PHPStan, and then thru the linter.

```
CMD.EXE was started with the above path as the current directory.
UNC paths are not supported.  Defaulting to Windows directory.
```

This part seems to be the error windows is having. TBH I'm not sure if this is an error with this linter or PHPStan since the nature of it seems related to how WSL works in windows. So I would suggest you look into that aspect of it and let us know if there's something that can be done to help address it.

**Comment by jt-github** [comment]
Upon further testing, this may be both a PHPStan issue _and_ an atom-linter-phpstan issue.  The latter because I suspect you're attempting to set the default directory when calling `phpstan.exe`.  That could be remedied by not trying to set the default directory at all (or use something like %systemroot%) and then calling phpstan directly on the file like `phpstan analyze \\sharename\full\file\path` or `phpstan analyze C:\what\ever`.

Of course, even that won't work right now since there is an issue with PHPStan itself.  When I tested by running the following at a command prompt in my C:\Users\me folder:
`phpstan analyze \\wsl$\CentOS7\my\files\here\blah.php`
it provided the following error message:
`Path C:\Users\me\wsl$\CentOS7\my\files\here\blah.php does not exist`

Poor ol' PHPStan is prepending the current directory to the UNC path.  No bueno.

Here's the issue I raised with PHPStan for this:
https://github.com/phpstan/phpstan/issues/3560

**Comment by jt-github** [comment]
And wow, thanks for the fast response, @mallardduck !

**Comment by mallardduck** [comment]
It seems to me the root issue is about "WSL Interoperability" which I found a detailed resource on here: https://patrickwu.space/wslconf/

You may be able to create Wrappers the work around the issue you're hitting here, but I'm not 100% positive as I haven't used WSL for anything this complex.

**Comment by jt-github** [comment]
Until PHPStan supports UNC paths, this issue cannot move forward.  I'll report back once it's resolved.  I tested UNC without involving WSL by creating a local share on my PC and PHPStan failed the same way, so it does not appear to be an actual WSL issue (although that resource is a fantastic find - thanks!)

`C:\Users\me>type \\localhost\temp\test.php`
Result:
```
<?php

phpinfo();

?>
```

`C:\Users\me>phpstan analyze \\localhost\temp\test.php`
Result:
`Path C:\Users\me\localhost\temp\test.php does not exist`

**Comment by jt-github** [comment]
Unfortunately, I'm not getting a lot of traction on the PHPStan issue.  There was conversation for a while but now it's been silent for a week.  It seems that UNC is a big hairy deal as far as code revision goes...

**Comment by mallardduck** [comment]
@jt-github yes, I'm aware and would have to agree with their assessment. It's fallen silent as it's not possible to replicate or test as Ondrej explained and as I mentioned after some testing. Here:
> UPDATE: NVM after some testing and playing I cannot get the windows testing image to use \\localhost the same way it works on a "real" windows system.

https://github.com/phpstan/phpstan/issues/3560#issuecomment-655683239

I would also have to agree with their sentiment that you should adjust how your local system is configured to avoid the issue as they mention here:
>  You should find an alternative setup that either uses Linux paths starting with /, or traditional Windows paths starting with X:\ (any letter).

Frankly that's your issue to work though in the manner you are most comfortable. However if I were in your spot I would simply let the files "live" in windows - where Atom and the linter can fully access them - and worry about how to access them properly within WSL.

Given that WSL already maps your windows drives to regular linux paths it should be MUCH easier for you to create a Linux solution to get those files accessible how ever you need. I.e. just symlink or bind mount the folder from where WSL automatlically will mount it to where ever you need.

**Comment by mallardduck** [comment]
So I'm not sure if this is still an issue for you @jt-github - but if it is there may be a way to work on it finally.
From what I see in the GitHub docs, the windows worker should have access to WSL now: https://github.com/actions/virtual-environments/blob/main/images/win/Windows2019-Readme.md

If it does have WSL access then in theory it should have access to the same WSL path you were using to try to reach your code. In that case there could be a failing test for WSL via UNC paths made in PHPstan for them to fix upstream. Is this still a concern for you?
