### ISSUE TITLE
Configuration file does not appear to be used

### ISSUE THREAD

**Issue by ghost** [BradCrumb/atom-linter-phpstan#2]
I'm experiencing an issue where my config file at my project root is not being used. As a result, I'm getting errors due to a missing PHPStan extension (PHPUnit) that don't show when I manually run PHPStan on the command line.

I'm using the setting to automatically detect the appropriate configuration file. I've stepped through the code using the debugger and see that the `confFile` is correctly detected and found. However, it is only used as working directory afterwards, which does not appear to be sufficient. On the command line, I apparently need to pass `--configuration=phpstan.neon` explicitly for it to be used - apparently PHPStan 0.9.2 is not smart enough (yet) to check the current working directory.

Thanks!

**Comment by BradCrumb** [comment]
Hi @tominventisbe ,

Thank you for your analyses. I just released version 1.0.2 with the --configuration option. This was indeed a bug.

The strange thing is that the documentation of PHPStan says: "If you do not provide config file explicitly, PHPStan will look for files named phpstan.neon or phpstan.neon.dist in current directory.". I just tested it and indeed it doesn't work.
